#!/bin/sh

mkdir -p /proc
mkdir -p /tmp
mkdir -p /sys

mount -t proc proc /proc
mount -t tmpfs tmpfs /tmp
mount -t sysfs sysfs /sys

mdev -s

while [ 1 ]; do
  echo "Hello world"
  exec /bin/sh
done

